### PR TITLE
Delete temporary files on error, refs #200

### PR DESCRIPTION
**Pull request by clochix**

### CODE REVIEW

**Comment by frankrousseau** [comment]
@clochix Your PR breaks tests. Can you fix that?

**Comment by clochix** [comment]
Tests are only broken with node 0.12 but pass with 0.10, 4 and 5. Could we try to launch Travis again?

**Comment by nono** [comment]
@clochix yes, I've restarted the tests for node 0.12. The broken test looks like the typical slowdown of travis (timeout).

**Comment by nono** [comment]
And it's green

**Pull request merged**
