### PR TITLE
Bugfix/117

### LINKED ISSUE #80: Displaying number of photos per album: cases < 2 should be managed
When there is only 1 or even 0 photo in an album, the interface shows "1 photos" and "0 photos".
Singular and zero cases should be managed with " 1 photo" an "no photo" 
I suppose the issue can be fixed in app/templates/album.jade around line 35 
1photos
singulier_0photos

### PR DESCRIPTION
**Pull request by 0gust1**
- polyglot version update 0.2.0 => 1.0.0
- pluralization rules management
- manage instantly counter plural

Should close #80 (almost) and #117

### CODE REVIEW

**Comment by nono** [comment]
Thanks for your contribution. It has been merged in development.

**Comment by 0gust1** [comment]
C

**Comment by 0gust1** [comment]
Closing the PR, as it was merged in an other way

**Comment by aenario** [comment]
Hi @0gust1, your changes have been released as v1.0.20.

Thanks again.

**Pull request closed without merging**
