### PR TITLE
Really minor fixes

### PR DESCRIPTION
**Pull request by clochix**
- CSS fixes to add a scrollbar to the modal window used to select contacts for sharing. If we select a lot of contacts, the list was grouwing outside the window, whose max height is fixed;
- fix a template, removing a parenthesis inside the name of the default image;

### CODE REVIEW

**Comment by frankrousseau** [comment]
The problem with overflow is that you can't see the auto-complete widget when it's on. I don't know how to handle both cases.

**Comment by clochix** [comment]
Another try to fix the overflow problem, seems to work for me, would you mind to give it a try?

**Comment by frankrousseau** [comment]
Here is my feedback:
- Putting loading image as a background was a bad idea: it doesn't work well with PNG (transparent background).
- The loading image is displayed on hover in the album item list.

**Comment by clochix** [comment]
- I now remove the background image once image is loaded;
- fixed the :hover bug;

**Comment by frankrousseau** [comment]
The photo loading progress bar is broken. I can't merge this PR. I wait for your fix.

**Comment by frankrousseau** [comment]
Thank you, it works fine.

**Pull request merged**
