### PR TITLE
fix album creation

### PR DESCRIPTION
**Pull request by frankrousseau**
I thought my previous PR fixed all of that, but that wasn't the case. Here are the fixed bugs.
- photo can be uploaded
- ui doesn't change when title is edited
- cover picture is automatically set

### CODE REVIEW

**Comment by jsilvestre** [comment]
I haven't succeeded in uploading a picture. (my DS is on upstream/master if it helps)
- When I try to upload a picture
- The preview is shown, and then instantly disappears.
- The server has crashed, if I restart it, the picture has not been uploaded

Browser console output:

```
POST http://localhost:9119/photos net::ERR_CONNECTION_REFUSED jquery-1.9.1.js:8526
WARNING: Missing translation for key: " : upload failled" polyglot.js:230
 : upload failled photoprocessor.coffee:165
GET http://localhost:9119/img/error.gif net::ERR_CONNECTION_REFUSED 
```

Server output:

```
[2014-10-13 18:06:40:824] info - americano | cozy-photos server is listening on port 9119...
GET /? 304 152.101 ms - -
GET /clearance/contacts 304 120.845 ms - -
GET /albums/5478f2934af3d87b0d7bb7fb7c00760c 200 101.135 ms - 120
PUT /albums/5478f2934af3d87b0d7bb7fb7c00760c 200 48.133 ms - 156

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:988:11)
  at Process.ChildProcess._handle.onexit (child_process.js:779:34)
(server has crashed at this point)
```

**Comment by frankrousseau** [comment]
It looks like a folder is missing. I will make another try from a new git clone.

**Comment by jsilvestre** [comment]
Ok, I installed imagemagick on my computer and it's now working. Should we add a note into the readme?

**Comment by jsilvestre** [comment]
In the album edit screen, the number of pictures is not updated after an upload or a deletion. Do you want me to open a new issue or do you plan to fix it in this PR?

**Pull request merged**
